// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5Obigtik6QfPjfXJbfWtn7_ksZZeQPxQ',
    appId: '1:13180334911:web:d7c00b9c435a046ce8198a',
    messagingSenderId: '13180334911',
    projectId: 'flicker-play',
    authDomain: 'flicker-play.firebaseapp.com',
    storageBucket: 'flicker-play.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6-0mPIndGhvDEXI9KP4bo5gS6nxZyQ_c',
    appId: '1:13180334911:android:dbacaaa1a127cc90e8198a',
    messagingSenderId: '13180334911',
    projectId: 'flicker-play',
    storageBucket: 'flicker-play.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiXJyGSkh6piovLq3mbs2K1VGvSl-Nwxg',
    appId: '1:13180334911:ios:f901534eb5f19726e8198a',
    messagingSenderId: '13180334911',
    projectId: 'flicker-play',
    storageBucket: 'flicker-play.appspot.com',
    iosBundleId: 'com.example.flickerPlay',
  );
}
